# .github/workflows/process_and_upload.yml

name: Process and Upload to Hugging Face

on:
  push:
    branches:
      - main  # או master, בהתאם לענף הראשי שלך
  
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    
    steps:
      # שלב 1: שכפול הריפו עם תמיכה מלאה ב-Git LFS
      # הוספנו 'lfs: true' כדי להוריד את התוכן המלא של הקבצים ולא רק מצביעים.
      - name: Checkout repository with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      # שלב 2: הגדרת סביבת פייתון, שימוש בגרסה 5 של הפעולה
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # שלב 3: התקנת הספריות הנדרשות
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datasets huggingface_hub

      # שלב 4: הרצת סקריפט העיבוד וההעלאה
      - name: Run processing and upload script
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: python process_and_upload.py
