name: Update Files Manifest

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          repository: Sivan22/otzaria-library
          fetch-depth: 1
          sparse-checkout: |
            links
            אוצריא

      - name: Generate Files Manifest
        run: |
          echo '{' > files_manifest.json
          find . -type f \
            ! -path "./.git/*" \
            ! -path "./.github/*" \
            ! -name "files_manifest.json" \
            -printf '"%P": {"modified": "%TY-%Tm-%Td %TH:%TM:%TS"},' | \
            sed '$ s/,$//' >> files_manifest.json
          echo '}' >> files_manifest.json

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update files manifest'
          add: 'files_manifest.json'
